# Generated by Django 4.2.10 on 2024-08-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(default=None, max_length=250, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
